### ISSUE TITLE
Rollup for v 0.1.0 Release

### ISSUE THREAD

**Issue by beardedtim** [beardedtim/cms-server#5]
## Overview

Now that we have a configurable way to create servers, we should release it to the public and try to get feedback so we can perfect the system. While it will never be perfect, I think the best way to make it better is to get people breaking it. 

## Checklist

v 0.0.1 will be ready for release when:
- [x] We can install the package from NPM
- [x] README is up-to-date
- [ ] We have a web page/github page for the docs
- [ ] We have a dummy web page working for users to interact with

## PRs

- [ ] #4 - Stable API : Review Needed

**Comment by LanceJernigan** [comment]
For the readme, it mentions the full CMS, are we wanting to just wrap up the server part or, indeed, the full CMS?

**Comment by beardedtim** [comment]
@LanceJernigan I am thinking that this will solely take in a config and create the needed server/microservices. So not the full CMS, just the server part wrapped and ready to be used. Thoughts on that?

**Comment by LanceJernigan** [comment]
@beardedtim That's what I was thinking.  I was just checking because it still had the full CMS writeup for the readme and I didn't want to remove anything that was needed because I was fixing to try to clean that up.

**Comment by LanceJernigan** [comment]
There are currently inconsistencies with naming for the package.  In npm, the package is `cms`, this repository is `cms-server` and in the readme, we reference it as `cms`.  We need to decide if we are naming it `cms` or `cms-server` and update all the references to match.

Once we decide on that, we can either update the repository name or the readme/npm and mark those two off the above list.

**Comment by beardedtim** [comment]
I say go with `server` as that is all we have ready.

**Comment by LanceJernigan** [comment]
Do you want to take care of updating the npm package and I'll take care of the readme?

**Comment by beardedtim** [comment]
> Do you want to take care of updating the npm package and the repository description 

I'll update the info for `npm` before pushing 👍

**Comment by beardedtim** [comment]
Name, description, and keywords updated inside of `package.json`. That file should be ready for release
