### ISSUE TITLE
No Error Message

### ISSUE THREAD

**Issue by LanceJernigan** [beardedtim/cms-server#6]
I sent a post request to `/documents` but instead of getting a response from the server, I just got a 'Not Found' message in PostMan.

**Comment by beardedtim** [comment]
This should be fixed in #4

**Comment by LanceJernigan** [comment]
This seems to still be an issue in #4.

**Comment by beardedtim** [comment]
Can you look into why? I thought I had it fixed with the last commit. I might have forgot to commit/push something. 

Any help on that would be great as I'm away for the rest of the day.

**Comment by beardedtim** [comment]
Are you getting a 404 or are you just getting the string "not found"?

**Comment by LanceJernigan** [comment]
It's registering as a 404, but our server isn't sending an actual error object back.

**Comment by beardedtim** [comment]
How are you trying it? Which example repo?

**Comment by LanceJernigan** [comment]
No example repo, just running it from the root folder.  It works with a `get` request, but fails when I send a`post` request.  I fixed an error handling step that was getting skipped so I get an actual error object back, now.

Now, I'm getting a 500 'argument req is required to be an object' error I'm trying to work out.

**Comment by LanceJernigan** [comment]
It looks like the authorization is failing on `post` requests because I get a response when I disable the `ensureAuthorized` step for the post method.

**Comment by LanceJernigan** [comment]
Nevermind, I'm just a big dummy and was working on the wrong branch.  ¯\_(ツ)_/¯
