### ISSUE TITLE
Issue installing via yarn

### ISSUE THREAD

**Issue by LanceJernigan** [beardedtim/cms-server#7]
`yarn add @beardedtim/cms`

yields

`error @beardedtim/cms@0.0.1: The engine "node" is incompatible with this module. Expected version "7.9.0".`
`error Found incompatible module`

**Comment by beardedtim** [comment]
Try the following:

`nvm use 7.9.0`

If that doesn't work ( you might need to install it if you don't already have 7.9.0 installed via `nvm` ), I can change/remove the `engine` field

**Comment by LanceJernigan** [comment]
That works.

We either need to`either` mention somewhere (probably the `readme.md`) that the current version only support 7.9.0 `or` get it working on other versions, too.

**Comment by beardedtim** [comment]
Want to make the changes to the README along with adding an `.nvmrc` file that is set to `7.9.0`?
