### ISSUE TITLE
npm currently downloads examples inside the package.

### ISSUE THREAD

**Issue by LanceJernigan** [beardedtim/cms-server#8]

**Comment by beardedtim** [comment]
I noticed this. I think I am okay with that as it's like 10 text files, all about 10 lines long. So it is basically a "tutorial" file but split up. Thoughts?

**Comment by LanceJernigan** [comment]
I'm leaning more towards splitting them.  If a user is installing the package to use the `cms-server` part (just importing it into their working project), these 100 lines of code are just sitting in the background doing nothing without the user even knowing they are there.

Even if a user knows the examples exist, they would have to navigate into the package inside `node_modules` and make changes which I generally think of as bad practice (I could be wrong on that).

**Comment by beardedtim** [comment]
Added `.npmignore` to #4
